# Generated by Django 4.2.5 on 2023-10-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom_app', '0002_sbom_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='searche_data',
            fields=[
                ('id', models.BigIntegerField(primary_key='True', serialize=False)),
                ('cve_id', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sbom_data',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sbom_data',
            name='version',
            field=models.TextField(),
        ),
    ]
