# Generated by Django 4.2.5 on 2023-10-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbom_app', '0004_alter_searche_data_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searche_data',
        ),
    ]
