# Generated by Django 4.2.5 on 2023-10-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom_app', '0005_delete_searche_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='searche_data',
            fields=[
                ('id', models.BigIntegerField(primary_key='False', serialize=False)),
                ('cve_id', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
        ),
    ]
