# Generated by Django 4.2.5 on 2023-10-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom_app', '0008_cvedata_parsingcvedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbomAppSbomData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('version', models.TextField()),
            ],
            options={
                'db_table': 'sbom_app_sbom_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='sbom_data',
        ),
    ]
