# Generated by Django 4.2.5 on 2023-10-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbom_app', '0009_sbomappsbomdata_delete_sbom_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbomappsbomdata',
            options={},
        ),
    ]
