# Generated by Django 4.2.5 on 2023-10-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbom_app', '0010_alter_sbomappsbomdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbomappsbomdata',
            options={'managed': False},
        ),
    ]
