# Generated by Django 4.2.5 on 2023-10-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom_app', '0011_alter_sbomappsbomdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbomVulData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(blank=True, db_column='CVE_ID', max_length=20, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
