# Generated by Django 4.2.5 on 2023-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom_app', '0012_sbomvuldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbomvuldata',
            name='cve_id',
        ),
        migrations.AddField(
            model_name='sbomvuldata',
            name='cve',
            field=models.CharField(blank=True, db_column='cve', max_length=20, null=True),
        ),
    ]
